export type ThemeParam =
    | 'baseButton'
    | 'baseButtonDisabled'
    | 'baseDropdownInputContainer'
    | 'baseDropdownInputText'
    | 'baseDropdownMenuContainer'
    | 'baseDropdownMenuHeader'
    | 'baseDropdownMenuItem'
    | 'baseDropdownMenuItemActiveButton'
    | 'baseDropdownMenuItemButton'
    | 'baseDropdownMenuItemGroup'
    | 'baseDropdownMenuItemIcon'
    | 'baseDropdownMenuItems'
    | 'baseDropdownMenuTriggerButton'
    | 'baseTypeaheadContainer'
    | 'buttonComboDropdownPrimaryButton'
    | 'buttonComboDropdownTriggerButton'
    | 'buttonComboDropdownTriggerButtonIcon'
    | 'columnManagerContainer'
    | 'columnManagerGroupContainer'
    | 'columnManagerGroupHeader'
    | 'columnManagerGroupsContainer'
    | 'columnManagerItem'
    | 'columnManagerNewGroupContainer'
    | 'columnManagerNewGroupInput'
    | 'columnManagerNewGroupInputButton'
    | 'comboboxFloatingPanelContainer'
    | 'generalFloatingPanelContainer'
    | 'inputText'
    | 'modalMainContainer'
    | 'modalMainContentContainer'
    | 'modalScrollContainer'
    | 'settingsMainContentContainer'
    | 'settingsMenuContainer'
    | 'settingsMenuGroupContainer'
    | 'settingsMenuItem'
    | 'settingsMenuItemActive'
    | 'settingsMenuItemIcon'
    | 'tabsNavLine'
    | 'tabsNavTab'
    | 'uiWindowToolbarTopMenuEnabled'
    | 'uiWindowToolbarWindowCloseButton'
    | 'uiWindowToolbarWindowContainer'
    | 'uiWindowToolbarWindowTopMenu'
    | 'uiWindowToolbarWindowTopMenuTitle'

export type ThemeParams = {
    baseButton: string
    baseButtonDisabled: string
    baseDropdownInputContainer: string
    baseDropdownInputText: string
    baseDropdownMenuContainer: string
    baseDropdownMenuHeader: string
    baseDropdownMenuItem: string
    baseDropdownMenuItemActiveButton: string
    baseDropdownMenuItemButton: string
    baseDropdownMenuItemGroup: string
    baseDropdownMenuItemIcon: string
    baseDropdownMenuItems: string
    baseDropdownMenuTriggerButton: string
    baseTypeaheadContainer: string
    buttonComboDropdownPrimaryButton: string
    buttonComboDropdownTriggerButton: string
    buttonComboDropdownTriggerButtonIcon: string
    columnManagerContainer: string
    columnManagerGroupContainer: string
    columnManagerGroupHeader: string
    columnManagerGroupsContainer: string
    columnManagerItem: string
    columnManagerNewGroupContainer: string
    columnManagerNewGroupInput: string
    columnManagerNewGroupInputButton: string
    comboboxFloatingPanelContainer: string
    generalFloatingPanelContainer: string
    inputText: string
    modalMainContainer: string
    modalMainContentContainer: string
    modalScrollContainer: string
    settingsMainContentContainer: string
    settingsMenuContainer: string
    settingsMenuGroupContainer: string
    settingsMenuItem: string
    settingsMenuItemActive: string
    settingsMenuItemIcon: string
    tabsNavLine: string
    tabsNavTab: string
    uiWindowToolbarTopMenuEnabled: boolean
    uiWindowToolbarWindowCloseButton: string
    uiWindowToolbarWindowContainer: string
    uiWindowToolbarWindowTopMenu: string
    uiWindowToolbarWindowTopMenuTitle: string
}
