export const ThemeCore: any = {
    baseButton: 'flex items-center rounded-md font-medium leading-none',
    baseButtonDisabled: 'pointer-events-none opacity-60',
    baseDropdownMenuContainer: 'relative inline-block text-left',
    baseDropdownMenuHeader: '',
    baseDropdownMenuItem: '',
    baseDropdownMenuItemActiveButton: '',
    baseDropdownMenuItemButton: '',
    baseDropdownMenuItemIcon: '',
    baseDropdownMenuItems: '',
    baseDropdownMenuTriggerButton: '',
    columnManagerContainer: 'flex h-full',
    columnManagerGroupContainer: '',
    columnManagerGroupHeader: '',
    columnManagerGroupsContainer: '',
    columnManagerNewGroupContainer: '',
    columnManagerNewGroupInput: '',
    columnManagerNewGroupInputButton: '',
}
